### ISSUE TITLE
When a game's price is in discount, the returned price value is the original price string concatenated with the discount price

### ISSUE THREAD

**Issue by darkred** [alosarjos/steam-provider#1]
Greetings

First of all, thank you for making this great steam information provider, @alosarjos . Exactly what I was looking for!

Just one thing I noticed:
when a game's price is in discount, the returned price value is the original price string concatenated with the discount price.

e.g. for http://store.steampowered.com/app/726950/Dark_Rose_Valkyrie/, i.e. http://store.steampowered.com/api/appdetails?appids=726950
the price has become <strike>$39.99</strike> --> $31.99

but the returned value is `39.9931.99` :
```json
SteamSearchEntry {
  id: '726950',
  name: 'Dark Rose Valkyrie',
  url: 'http://store.steampowered.com/app/726950/Dark_Rose_Valkyrie/?snr=1_7_7_151_150_1',
  price: '39.9931.99',
  score: '' }
```

_For reference, the code I used (node 9.11.1)_
```javascript
var steam = require('steam-provider');
var provider = new steam.SteamProvider();
provider.search('Dark Rose Valkyrie').then(result => {
	console.log(result[0]);
});
```

&nbsp;

**Could steam-provider be changed so that the combined 'price' key to be split into something like:** 
```json
price_original: '39.99',
price_with_discount: '31.99'.
```

**Comment by alosarjos** [comment]
I just uploaded version 0.0.5. It should fix your problems :)

With your test (Now the game is at normal price)


```javascript
SteamSearchEntry {
  id: '726950',
  name: 'Dark Rose Valkyrie',
  url: 'http://store.steampowered.com/app/726950/Dark_Rose_Valkyrie/?snr=1_7_7_151_150_1',
  price: '39.99',
  priceWithDiscount: '',
  score: '' }
```

With Darkest Dungeon (it's on sale right now)
```javascript
SteamSearchEntry {
  id: '262060',
  name: 'Darkest Dungeon®',
  url: 'http://store.steampowered.com/app/262060/Darkest_Dungeon/?snr=1_7_7_151_150_1',
  price: '$24.9',
  priceWithDiscount: '$8.49',
  score: '' }
```

Now, I'm doubting if I should keep or not the currency symbol...

**Comment by darkred** [comment]
Thank you very much for the quick fix !

**Comment by darkred** [comment]
> Now, I'm doubting if I should keep or not the currency symbol...

IMHO you should keep it.
I think currently it's not possible to make a query in steam-provider asking prices in currency different than USD. Am I right?

**Comment by alosarjos** [comment]
Both, detail and search function have optional parameters for language and currency, which are by default for US and English. Because of how on some languages the symbol in on the right side or the left side, it could bring problems for other currencies. For now this is a quick fix.

**Comment by darkred** [comment]
> Both, detail and search function have optional parameters for language and currency, which are by default for US and English. 

Do you mean that the these optional parameters are hard coded inside the source code ([steam-provider.ts](https://github.com/alosarjos/steam-provider/blob/master/src/services/steam/providers/steam-provider.ts)) ?
Or could I modify my above code to define optional parameters e,g. for currency?
```javascript
var steam = require('steam-provider');
var provider = new steam.SteamProvider();
provider.search('Dark Rose Valkyrie').then(result => {
	console.log(result[0]);
});
```
_I couldn't find any relevant info in README.md or https://github.com/alosarjos/steam-provider/blob/master/src/services/steam/providers/steam-provider.ts_

**Comment by alosarjos** [comment]
It can be done like this:


provider.search("Darkest Dungeon", "spanish", "es").then(result => {
    console.log(result)
})

For spanish prices, for example. The problem is that, with the fix for the discount prices I did, now that part it's broken. (Check that example). I will look into it when I can.


And yeah, sorry, I should have updated that README....

**Comment by darkred** [comment]
Thanks again.
